
# syntax = docker/dockerfile:1

# Make sure RUBY_VERSION matches the Ruby version in .tool-versions and Gemfile
ARG RUBY_VERSION=3.4.4
ARG VARIANT=bookworm

################################################################################
# 1. Build stage
FROM ruby:$RUBY_VERSION-$VARIANT AS build

# Set the BUNDLE_PATH environment variable
ENV BUNDLE_PATH /usr/local/bundle

# Install build dependencies
RUN apt-get update -qq &&     apt-get install -y --no-install-recommends build-essential libpq-dev nodejs npm libvips-dev

# Copy application code
WORKDIR /app
COPY . .

# Install gems
RUN bundle install

# Install node modules
RUN npm install

# Precompile assets
RUN SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile

################################################################################
# 2. Runtime stage
FROM ruby:$RUBY_VERSION-$VARIANT AS runtime

# Install runtime dependencies
RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends libpq-dev libvips42 && \
    rm -rf /var/lib/apt/lists/*

# Create a non-root user
RUN useradd --create-home --shell /bin/bash app
WORKDIR /home/app

# Copy application code and dependencies from build stage
COPY --from=build /app /home/app
COPY --from=build /usr/local/bundle /usr/local/bundle

# Set ownership and permissions
RUN chown -R app:app /home/app /usr/local/bundle
USER app

# Expose port 3000
EXPOSE 3000

# Set entrypoint and command
ENTRYPOINT ["/home/app/bin/docker-entrypoint.gmt.sh"]
CMD ["./bin/rails", "server"]

